# Generated by Django 5.2.4 on 2026-01-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('category', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/original/')),
                ('video_480p', models.FileField(blank=True, null=True, upload_to='videos/480p/')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to='videos/720p/')),
                ('video_1080p', models.FileField(blank=True, null=True, upload_to='videos/1080p/')),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
    ]
