# Generated by Django 5.2.4 on 2026-01-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='videos/default.mp4', upload_to='videos/'),
        ),
    ]
