# Generated by Django 5.2.4 on 2026-01-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0002_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/original/'),
        ),
    ]
