# Generated by Django 5.2.4 on 2026-01-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0003_video_video_1080p_video_video_480p_video_video_720p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
